modLoader = "javafml"
loaderVersion = "[40,)"
license = "All Rights Reserved"

[[mods]]
modId = "enchanted"
version = "${version}"
displayName = "${mod_name}"
credits = "Heavily inspired by Emoniph's Witchery mod"
authors = "Favouriteless"
description = '''Enchanted is your mod for all things occult or witchcraft. A modernized attempt at Emoniph's Witchery.'''
logoFile = "icon.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/enchanted-witchcraft" #optional

[[dependencies.enchanted]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.enchanted]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,)"
    ordering = "NONE"
    side = "BOTH"