modLoader = "javafml"
loaderVersion = "${fml_version_range}"
license = "${license}"


[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    displayURL= "${display_url}"
    logoFile = "${mod_id}.png"
    credits = "${credits}"
    authors = "${author}"
    description = '''${description}'''

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${minecraft_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "geckolib4"
    mandatory = true
    versionRange = "[${geckolib_forge_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "patchouli"
    mandatory = true
    versionRange = "[${patchouli_forge_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "stateobserver"
    mandatory = true
    versionRange = "[${stateobserver_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.enchanted]]
    modId = "smartbrainlib"
    mandatory = true
    versionRange = "[${sbl_version},)"
    ordering = "NONE"
    side = "BOTH"