modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"


[[mods]]
modId = "enchanted"
version = "2.0.0"
displayName = "Enchanted"
displayURL= "https://www.curseforge.com/minecraft/mc-mods/enchanted-witchcraft"
logoFile = "enchanted.png"
credits = "Heavily inspired by Emoniph's Witchery mod"
authors = "Favouriteless"
description = '''Enchanted is your mod for all things occult or witchcraft.'''

[[dependencies.enchanted]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.enchanted]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,)"
    ordering = "NONE"
    side = "BOTH"
