modLoader="javafml" #mandatory

loaderVersion="[36,)"

license="GNU GPLv3"

[[mods]] #mandatory

modId="enchanted" #mandatory

version="${file.jarVersion}" #mandatory
displayName="Enchanted" #mandatory
logoFile="icon.png" #optional

credits="Heavily inspired by Emoniph's Witchery mod" #optional
authors="Favouriteless" #optional

description='''
Enchanted is your mod for all things occult or witchcraft. A modernized attempt at Emoniph's Witchery.
'''

[[dependencies.enchanted]]
    modId="observerlib"
    mandatory=true
    versionRange="[1.16.5-1.5,]"
    ordering="NONE"
    side="BOTH"