modLoader="javafml" #mandatory

loaderVersion="[36,)"

license="All rights reserved"

[[mods]] #mandatory

modId="enchanted" #mandatory

version="${file.jarVersion}" #mandatory
displayName="Enchanted" #mandatory
logoFile="examplemod.png" #optional

credits="Heavily inspired by Emoniph's Witchery mod" #optional
authors="Favouriteless" #optional

description='''
Enchanted is your mod for all things occult or witchcraft. A modernized attempt at Emoniph's Witchery.
'''
