modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory

license="GNU GPLv3"

[[mods]] #mandatory

modId="enchanted" #mandatory

version="${file.jarVersion}" #mandatory
displayName="Enchanted" #mandatory
logoFile="icon.png" #optional

credits="Heavily inspired by Emoniph's Witchery mod" #optional
authors="Favouriteless" #optional

description='''
Enchanted is your mod for all things occult or witchcraft. A modernized attempt at Emoniph's Witchery.
'''

[[dependencies.enchanted]]
modId="observerlib"
mandatory=true
versionRange="[1.18.2-1.6.0,]"
ordering="NONE"
side="BOTH"
[[dependencies.enchanted]]
modId="patchouli"
mandatory=true
versionRange="[1.18.2-71.1,]"
ordering="NONE"
sides="BOTH"
