package com.favouriteless.enchanted.datagen.providers.loot_tables;

import com.favouriteless.enchanted.common.blocks.crops.CropsBlockAgeFive;
import com.favouriteless.enchanted.common.init.registry.EnchantedBlocks;
import com.favouriteless.enchanted.common.init.registry.EnchantedItems;
import com.favouriteless.enchanted.common.init.registry.util.BlockRegistryDescriptor.LootInfo;
import com.favouriteless.enchanted.common.init.registry.util.BlockRegistryDescriptor.LootType;
import com.favouriteless.enchanted.platform.services.ForgeCommonRegistryHelper;
import net.minecraft.advancements.critereon.ItemPredicate;
import net.minecraft.advancements.critereon.StatePropertiesPredicate;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.enchantment.Enchantments;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.ApplyBonusCount;
import net.minecraft.world.level.storage.loot.predicates.BonusLevelTableCondition;
import net.minecraft.world.level.storage.loot.predicates.LootItemBlockStatePropertyCondition;
import net.minecraft.world.level.storage.loot.predicates.LootItemCondition;
import net.minecraft.world.level.storage.loot.predicates.MatchTool;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import net.minecraftforge.registries.RegistryObject;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.function.Supplier;

public class BlockLootSubProvider extends net.minecraft.data.loot.BlockLootSubProvider {

    private static final Map<Supplier<? extends Block>, LootInfo> autoGenerated = new HashMap<>();

    public BlockLootSubProvider() {
        super(Collections.emptySet(), FeatureFlags.REGISTRY.allFlags());
    }

    @Override
    protected void generate() {
        for(Entry<Supplier<? extends Block>, LootInfo> entry : autoGenerated.entrySet()) {
            Block block = entry.getKey().get();
            LootInfo info = entry.getValue();

            add(block, b -> {
                ItemLike out = info.type == LootType.SELF ? b : info.drop.get();
                LootPool.Builder pool = LootPool.lootPool()
                        .setRolls(ConstantValue.exactly(1.0F))
                        .add(LootItem.lootTableItem(out));

                if(info.tools != null)
                    pool.when(MatchTool.toolMatches(ItemPredicate.Builder.item().of(Arrays.stream(info.tools).map(Supplier::get).toArray(ItemLike[]::new))));

                if(info.silk)
                    pool.when(HAS_SILK_TOUCH);
                return LootTable.lootTable().withPool(pool);
            });


            switch(info.type) {
                case SELF -> dropSelf(block);
                case OTHER -> dropOther(block, info.drop.get());
            }
        }

        add(EnchantedBlocks.ROWAN_LEAVES.get(), block -> createFruitLeavesDrop(block, EnchantedBlocks.ROWAN_SAPLING.get(), EnchantedItems.ROWAN_BERRIES.get(), NORMAL_LEAVES_SAPLING_CHANCES));
        add(EnchantedBlocks.ALDER_LEAVES.get(), block -> createLeavesDrops(block, EnchantedBlocks.ALDER_SAPLING.get(), NORMAL_LEAVES_SAPLING_CHANCES));
        add(EnchantedBlocks.HAWTHORN_LEAVES.get(), block -> createLeavesDrops(block, EnchantedBlocks.HAWTHORN_SAPLING.get(), NORMAL_LEAVES_SAPLING_CHANCES));
        add(EnchantedBlocks.ALDER_SLAB.get(), this::createSlabItemTable);
        add(EnchantedBlocks.HAWTHORN_SLAB.get(), this::createSlabItemTable);
        add(EnchantedBlocks.ROWAN_SLAB.get(), this::createSlabItemTable);
        createCropBlockAgeFiveDrops(EnchantedBlocks.ARTICHOKE.get(), EnchantedItems.ARTICHOKE.get(), EnchantedItems.ARTICHOKE_SEEDS.get());
        createCropBlockAgeFiveDrops(EnchantedBlocks.BELLADONNA.get(), EnchantedItems.BELLADONNA_FLOWER.get(), EnchantedItems.BELLADONNA_SEEDS.get());
        createCropBlockAgeFiveDrops(EnchantedBlocks.MANDRAKE.get(), EnchantedItems.MANDRAKE_ROOT.get(), EnchantedItems.MANDRAKE_SEEDS.get());
        createCropBlockAgeFiveDrops(EnchantedBlocks.WOLFSBANE.get(), EnchantedItems.WOLFSBANE_FLOWER.get(), EnchantedItems.WOLFSBANE_SEEDS.get());
        createDualCropBlockAgeFiveDrops(EnchantedBlocks.SNOWBELL.get(), EnchantedItems.ICY_NEEDLE.get(), Items.SNOWBALL, EnchantedItems.SNOWBELL_SEEDS.get());

        add(EnchantedBlocks.GARLIC.get(),
                applyExplosionDecay(EnchantedBlocks.GARLIC.get(),
                        LootTable.lootTable()
                                .withPool(LootPool.lootPool()
                                        .add(LootItem.lootTableItem(EnchantedItems.GARLIC.get())))
                                .withPool(LootPool.lootPool()
                                        .add(LootItem.lootTableItem(EnchantedItems.GARLIC.get())
                                        .when(LootItemBlockStatePropertyCondition.hasBlockStateProperties(EnchantedBlocks.GARLIC.get())
                                                .setProperties(StatePropertiesPredicate.Builder.properties().hasProperty(CropsBlockAgeFive.AGE_FIVE, 4)))
                                                .apply(ApplyBonusCount.addBonusBinomialDistributionCount(Enchantments.BLOCK_FORTUNE, 0.5714286F, 3))))
                )
        );
    }

    protected void createDualCropBlockAgeFiveDrops(Block block, ItemLike crop, ItemLike otherCrop, ItemLike seeds) {
        LootItemCondition.Builder ageCondition = LootItemBlockStatePropertyCondition.hasBlockStateProperties(block)
                .setProperties(StatePropertiesPredicate.Builder.properties().hasProperty(CropsBlockAgeFive.AGE_FIVE, 4));

        add(block, LootTable.lootTable().withPool(
                LootPool.lootPool()
                        .setRolls(ConstantValue.exactly(1.0F))
                        .add(LootItem.lootTableItem(seeds))
        ).withPool(
                LootPool.lootPool()
                        .setRolls(ConstantValue.exactly(1.0F))
                        .add(LootItem.lootTableItem(crop))
                        .add(LootItem.lootTableItem(otherCrop))
                        .when(ageCondition)
        ).withPool(
                LootPool.lootPool()
                        .setRolls(ConstantValue.exactly(1.0F))
                        .add(LootItem.lootTableItem(seeds)
                                .apply(ApplyBonusCount.addBonusBinomialDistributionCount(Enchantments.BLOCK_FORTUNE, 0.1714286F, 3)))
                        .when(ageCondition)
        ));
    }

    protected LootTable.Builder createFruitLeavesDrop(Block leaves, Block sapling, ItemLike fruit, float... chances) {
        return createLeavesDrops(leaves, sapling, chances)
                .withPool(
                        LootPool.lootPool()
                                .setRolls(ConstantValue.exactly(1.0F))
                                .when(HAS_SHEARS.or(HAS_SILK_TOUCH).invert())
                                .add(applyExplosionCondition(leaves, LootItem.lootTableItem(fruit))
                                        .when(BonusLevelTableCondition.bonusLevelFlatChance(Enchantments.BLOCK_FORTUNE, 0.005F, 0.0055555557F, 0.00625F, 0.008333334F, 0.025F))));
    }

    protected void createCropBlockAgeFiveDrops(CropsBlockAgeFive block, ItemLike crop, ItemLike seeds) {
        LootItemCondition.Builder itemCondition = LootItemBlockStatePropertyCondition.hasBlockStateProperties(block)
                .setProperties(StatePropertiesPredicate.Builder.properties().hasProperty(CropsBlockAgeFive.AGE_FIVE, 4));
        add(block, createCropDrops(block, crop.asItem(), seeds.asItem(), itemCondition));
    }

    @Override
    protected Iterable<Block> getKnownBlocks() {
        return ForgeCommonRegistryHelper.getRegistryMap().getDeferred(BuiltInRegistries.BLOCK).getEntries()
                .stream()
                .flatMap(RegistryObject::stream)
                ::iterator;
    }

    public static void addAuto(Supplier<? extends Block> block, LootInfo lootInfo) {
        autoGenerated.put(block, lootInfo);
    }

}
