modLoader = "javafml"
loaderVersion = "${neoforge_loader_range}"
license = "All Rights Reserved"


[[mods]]
    modId = "enchanted"
    version = "${version}"
    displayName = "Enchanted"
    displayURL= "https://github.com/Favouriteless/Enchanted"
    logoFile = "enchanted.png"
    credits = "Heavily inspired by Emoniph's Witchery mod"
    authors = "Favouriteless"
    description = '''Enchanted is your mod for all things occult or witchcraft.'''

[[mixins]]
    config="modopedia.neoforge.mixins.json"

[[dependencies.modopedia]]
    modId = "neoforge"
    type="required" #mandatory
    versionRange = "${neoforge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.modopedia]]
    modId = "minecraft"
    type="required" #mandatory
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"